/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"
#include "stm32f407xx_gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

_Bool Active = 0;

void delay(uint32_t x);

int main(void)
{
	// Driver Test Applications

	GPIO_PeriClockControl(GPIOD, ENABLE);
	GPIO_PeriClockControl(GPIOA, ENABLE);

	GPIO_Handle_t LED;
	GPIO_Handle_t *pLED = &LED;

	pLED->pGPIOx = GPIOD;

	pLED->GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT;
	pLED->GPIO_PinConfig.GPIO_PinOPType = GPIO_OTYPE_PUSHPULL;
	pLED->GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_NO;
	pLED->GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_13;

	GPIO_Handle_t Button;

	Button.pGPIOx = GPIOA;
	Button.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_0;
	Button.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FE;


	GPIO_Init(&Button);
	GPIO_Init(pLED);

	GPIO_IRQConfig(6, 15, ENABLE);

	//_Bool button;

	while(1)
	{
    //button = GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_0);
    	while(Active)
    	{
    		GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_13, SET);
    		delay(100000);
    		GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_13, RESET);
    		delay(100000);
    		//button = GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_0);
    	}
	}
    /* Loop forever */
	for(;;);
}

void delay(uint32_t x)
{
	for(uint32_t i=0 ; i< x; i++);
}

void EXTI0_IRQHandler(void)
{
	_Bool x = 1;
	while(x)
	{
		x = GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_0);

	}
	delay(10000);
	Active ^= 1;
	GPIO_IRQHandling(0);
}

